### PR TITLE
added NTSC test bars example

### PR DESCRIPTION
**Pull request by jedgarpark**
added the SMPTE NTSC color bars test example

### CODE REVIEW

**Review by kattni — COMMENTED** [review]
Looks good to me! Leaving approval for Limor.

**Comment by jedgarpark** [comment]
@ladyada not urgent, but please have a look when you get a chance, thanks

**Review by ladyada — APPROVED** [review]
tested! note that on my qt py esp the video comes out on A1 not A0?

**Comment by jedgarpark** [comment]
@ladyada freaky! I’ll check when I’m back — maybe I changed the pin number at some point when testing.

**Comment by jedgarpark** [comment]
@ladyada Ah, sure enough, I had changed to `DAC_CHANNEL_2` on mine, which outputs over `A0`. I'll leave the code at `DAC_CHANNEL_1` which is the library default and just update my fritzing and instructions to connect composite video output to `A1`
If you want to adjust this, it is in the **`ESP_8_BIT_composite.cpp`** file line `116`.

**Pull request merged**
